import React from "react";
import { View, Text, StyleSheet, ScrollView } from "react-native";

export default function AboutScreen() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>About This App</Text>

      <Text style={styles.paragraph}>
        This mobile application is designed to help identify the potential
        severity of Parkinson’s Disease using machine learning techniques.
        It provides an easy-to-use interface where users can input clinical
        voice measurements and receive predictions generated by an advanced
        severity estimation model.
      </Text>

      <Text style={styles.sectionTitle}>Our Purpose</Text>
      <Text style={styles.paragraph}>
        Parkinson’s Disease is a progressive neurological disorder that affects
        movement and speech. Early detection and continuous monitoring can
        greatly improve patient outcomes. This app aims to support medical
        professionals, caregivers, and researchers by offering a quick and
        accessible severity prediction tool.
      </Text>

      <Text style={styles.sectionTitle}>How the Model Works</Text>
      <Text style={styles.paragraph}>
        The ML model behind this application is trained on biomedical voice
        recordings containing features such as jitter, shimmer, frequency
        variation, and harmonics-to-noise ratio. These biomarkers have been
        widely studied for their correlation with Parkinson’s Disease symptoms.
      </Text>

      <Text style={styles.paragraph}>
        After processing the input values, the model predicts:
        {"\n"}• Motor UPDRS score{"\n"}• Total UPDRS score
      </Text>

      <Text style={styles.sectionTitle}>Why This Matters</Text>
      <Text style={styles.paragraph}>
        Accessibility and early monitoring tools empower patients and healthcare
        providers. Our goal is to make machine learning technology beneficial in
        real medical scenarios by simplifying the evaluation process and
        reducing assessment time.
      </Text>

      <Text style={styles.sectionTitle}>Disclaimer</Text>
      <Text style={styles.paragraph}>
        This application is intended for educational and research purposes only.
        It is not a substitute for professional medical diagnosis or clinical
        evaluation. Users should always consult a medical expert for accurate
        assessments and treatment decisions.
      </Text>

      <Text style={styles.footer}>
        © {new Date().getFullYear()} Parkinson Severity Prediction App
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    paddingBottom: 50,
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
  },
  footer: {
    marginTop: 40,
    textAlign: "center",
    fontSize: 14,
    color: "#888",
  },
});
